env:
    es6: true
    node: true
    mocha: true
extends:
    - 'eslint:recommended'
globals:
    Atomics: readonly
    SharedArrayBuffer: readonly
parserOptions:
    ecmaFeatures:
        jsx: true
    ecmaVersion: 2018
    sourceType: module
rules:
    arrow-spacing:
        - error
        - before: false
          after: false
    comma-spacing:
        - error
        - after: false
    comma-style:
        - error
        - last
    eol-last:
        - error
        - always
    indent:
        - error
        - 4
        - SwitchCase: 1
          VariableDeclarator: 1
          MemberExpression: 0
          FunctionDeclaration:
              body: 1
              parameters: off
          FunctionExpression:
              body: 1
              parameters: off
    key-spacing:
        - error
        - afterColon: false
    linebreak-style:
        - error
        - unix
    max-len:
        - error
        - code: 80
    no-multiple-empty-lines:
        - error
        - max: 1
          maxBOF: 0
    no-trailing-spaces:
        - error
        - skipBlankLines: true
    object-curly-spacing:
        - error
    quotes:
        - error
        - single
    semi:
        - error
        - always
    space-before-blocks:
        - error
        - never

